<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__CeorNjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ceorNj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..ceorNj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'motCle' => ['privates', '.errored..service_locator..ceorNj.App\\Entity\\MotCle', NULL, 'Cannot autowire service ".service_locator..ceorNj": it needs an instance of "App\\Entity\\MotCle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'motCle' => 'App\\Entity\\MotCle',
        ]);
    }
}
