<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GhgjJ8xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ghgjJ8x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statut' => ['privates', '.errored..service_locator.ghgjJ8x.App\\Entity\\Statut', NULL, 'Cannot autowire service ".service_locator.ghgjJ8x": it needs an instance of "App\\Entity\\Statut" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'statut' => 'App\\Entity\\Statut',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.ghgjJ8x'])) {
            return $container->privates['.service_locator.ghgjJ8x'];
        }

        return $container->privates['.service_locator.ghgjJ8x'] = $instance;
    }
}
