<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6u0cXBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6u0cX_B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livre' => ['privates', '.errored..service_locator.6u0cX_B.App\\Entity\\Livre', NULL, 'Cannot autowire service ".service_locator.6u0cX_B": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'livre' => 'App\\Entity\\Livre',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.6u0cX_B'])) {
            return $container->privates['.service_locator.6u0cX_B'];
        }

        return $container->privates['.service_locator.6u0cX_B'] = $instance;
    }
}
