<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z8dwEKqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z8dwEKq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'doctrine' => '?',
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.z8dwEKq'])) {
            return $container->privates['.service_locator.z8dwEKq'];
        }

        return $container->privates['.service_locator.z8dwEKq'] = $instance;
    }
}
