<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0X3XlXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0X3Xl_x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
        ], [
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'authChecker' => '?',
        ]);

        if (isset($container->privates['.service_locator.0X3Xl_x'])) {
            return $container->privates['.service_locator.0X3Xl_x'];
        }

        return $container->privates['.service_locator.0X3Xl_x'] = $instance;
    }
}
