<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteMotControllereditUnMotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PQP7fxl.App\Controller\DeleteMotController::editUnMot()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.PQP7fxl'] ?? $container->load('get_ServiceLocator_PQP7fxlService'));

        if (isset($container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::editUnMot()'])) {
            return $container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::editUnMot()'];
        }

        $instance = $a->withContext('App\\Controller\\DeleteMotController::editUnMot()', $container);

        if (isset($container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::editUnMot()'])) {
            return $container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::editUnMot()'];
        }

        return $container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::editUnMot()'] = $instance;
    }
}
