<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kRf_vBE.App\Controller\ErrorController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exception' => ['privates', '.errored..service_locator.kRf_vBE.Symfony\\Component\\ErrorHandler\\Exception\\FlattenException', NULL, 'Cannot autowire service ".service_locator.kRf_vBE": it references class "Symfony\\Component\\ErrorHandler\\Exception\\FlattenException" but no such service exists.'],
            'env' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'exception' => 'Symfony\\Component\\ErrorHandler\\Exception\\FlattenException',
            'env' => '?',
        ]))->withContext('App\\Controller\\ErrorController::show()', $container);

        if (isset($container->privates['.service_locator.kRf_vBE.App\\Controller\\ErrorController::show()'])) {
            return $container->privates['.service_locator.kRf_vBE.App\\Controller\\ErrorController::show()'];
        }

        return $container->privates['.service_locator.kRf_vBE.App\\Controller\\ErrorController::show()'] = $instance;
    }
}
