<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerdetailFicheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.byBXd2W.App\Controller\FicheController::detailFiche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'doctrine' => '?',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\FicheController::detailFiche()', $container);

        if (isset($container->privates['.service_locator.byBXd2W.App\\Controller\\FicheController::detailFiche()'])) {
            return $container->privates['.service_locator.byBXd2W.App\\Controller\\FicheController::detailFiche()'];
        }

        return $container->privates['.service_locator.byBXd2W.App\\Controller\\FicheController::detailFiche()'] = $instance;
    }
}
