<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerexportPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.alxzQ7..App\Controller\FicheController::exportPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.alxzQ7..App\\Controller\\FicheController::exportPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'pdfService' => 'App\\Service\\PdfService',
        ]))->withContext('App\\Controller\\FicheController::exportPdf()', $container);
    }
}
