<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerrechercheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KnUpfmw.App\Controller\FicheController::recherche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KnUpfmw.App\\Controller\\FicheController::recherche()'] = ($container->privates['.service_locator.KnUpfmw'] ?? $container->load('get_ServiceLocator_KnUpfmwService'))->withContext('App\\Controller\\FicheController::recherche()', $container);
    }
}
