<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerdeleteFicheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JOmvdPT.App\Controller\FicheController::deleteFiche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
        ], [
            'doctrine' => '?',
            'entityManager' => '?',
            'authChecker' => '?',
            'security' => '?',
            'ficheRepository' => 'App\\Repository\\FicheRepository',
        ]))->withContext('App\\Controller\\FicheController::deleteFiche()', $container);

        if (isset($container->privates['.service_locator.JOmvdPT.App\\Controller\\FicheController::deleteFiche()'])) {
            return $container->privates['.service_locator.JOmvdPT.App\\Controller\\FicheController::deleteFiche()'];
        }

        return $container->privates['.service_locator.JOmvdPT.App\\Controller\\FicheController::deleteFiche()'] = $instance;
    }
}
