<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GNxtwLt.App\Controller\FicheController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', false],
        ], [
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'entityManager' => '?',
            'authChecker' => '?',
            'livreRepository' => 'App\\Repository\\LivreRepository',
        ]))->withContext('App\\Controller\\FicheController::list()', $container);

        if (isset($container->privates['.service_locator.GNxtwLt.App\\Controller\\FicheController::list()'])) {
            return $container->privates['.service_locator.GNxtwLt.App\\Controller\\FicheController::list()'];
        }

        return $container->privates['.service_locator.GNxtwLt.App\\Controller\\FicheController::list()'] = $instance;
    }
}
