<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerdeleteFicheMotCleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J3N8_Pl.App\Controller\FicheController::deleteFicheMotCle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ficheMotCleRepository' => ['privates', 'App\\Repository\\FicheMotCleRepository', 'getFicheMotCleRepositoryService', true],
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'motCleRepository' => ['privates', 'App\\Repository\\MotCleRepository', 'getMotCleRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ficheMotCleRepository' => 'App\\Repository\\FicheMotCleRepository',
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'motCleRepository' => 'App\\Repository\\MotCleRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\FicheController::deleteFicheMotCle()', $container);

        if (isset($container->privates['.service_locator.J3N8_Pl.App\\Controller\\FicheController::deleteFicheMotCle()'])) {
            return $container->privates['.service_locator.J3N8_Pl.App\\Controller\\FicheController::deleteFicheMotCle()'];
        }

        return $container->privates['.service_locator.J3N8_Pl.App\\Controller\\FicheController::deleteFicheMotCle()'] = $instance;
    }
}
