<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerdetailFicheTotalRechService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z8dwEKq.App\Controller\FicheController::detailFicheTotalRech()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.z8dwEKq'] ?? $container->load('get_ServiceLocator_Z8dwEKqService'));

        if (isset($container->privates['.service_locator.z8dwEKq.App\\Controller\\FicheController::detailFicheTotalRech()'])) {
            return $container->privates['.service_locator.z8dwEKq.App\\Controller\\FicheController::detailFicheTotalRech()'];
        }

        $instance = $a->withContext('App\\Controller\\FicheController::detailFicheTotalRech()', $container);

        if (isset($container->privates['.service_locator.z8dwEKq.App\\Controller\\FicheController::detailFicheTotalRech()'])) {
            return $container->privates['.service_locator.z8dwEKq.App\\Controller\\FicheController::detailFicheTotalRech()'];
        }

        return $container->privates['.service_locator.z8dwEKq.App\\Controller\\FicheController::detailFicheTotalRech()'] = $instance;
    }
}
