<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\FicheRepository' shared autowired service.
     *
     * @return \App\Repository\FicheRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'FicheRepository.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\FicheRepository'])) {
            return $container->privates['App\\Repository\\FicheRepository'];
        }

        $instance = new \App\Repository\FicheRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['App\\Service\\SearchService'] ?? $container->load('getSearchServiceService')), $a);

        if (isset($container->privates['App\\Repository\\FicheRepository'])) {
            return $container->privates['App\\Repository\\FicheRepository'];
        }

        return $container->privates['App\\Repository\\FicheRepository'] = $instance;
    }
}
