<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vNjvjLJ.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.vNjvjLJ'] ?? $container->load('get_ServiceLocator_VNjvjLJService'));

        if (isset($container->privates['.service_locator.vNjvjLJ.App\\Controller\\HomeController::index()'])) {
            return $container->privates['.service_locator.vNjvjLJ.App\\Controller\\HomeController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\HomeController::index()', $container);

        if (isset($container->privates['.service_locator.vNjvjLJ.App\\Controller\\HomeController::index()'])) {
            return $container->privates['.service_locator.vNjvjLJ.App\\Controller\\HomeController::index()'];
        }

        return $container->privates['.service_locator.vNjvjLJ.App\\Controller\\HomeController::index()'] = $instance;
    }
}
