<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllermotsClesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fiyeSN7.App\Controller\IndexController::motsCles()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fiyeSN7.App\\Controller\\IndexController::motsCles()'] = ($container->privates['.service_locator.fiyeSN7'] ?? $container->load('get_ServiceLocator_FiyeSN7Service'))->withContext('App\\Controller\\IndexController::motsCles()', $container);
    }
}
