<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0ISXjwO.App\Controller\IndexController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0ISXjwO.App\\Controller\\IndexController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'index' => ['privates', '.errored..service_locator.0ISXjwO.App\\Entity\\Index', NULL, 'Cannot autowire service ".service_locator.0ISXjwO": it needs an instance of "App\\Entity\\Index" but this type has been excluded in "config/services.yaml".'],
        ], [
            'index' => 'App\\Entity\\Index',
        ]))->withContext('App\\Controller\\IndexController::show()', $container);
    }
}
