<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerexportPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X_mxZbC.App\Controller\IndexController::exportPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X_mxZbC.App\\Controller\\IndexController::exportPdf()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'indexRepository' => ['privates', 'App\\Repository\\IndexRepository', 'getIndexRepositoryService', true],
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'indexRepository' => 'App\\Repository\\IndexRepository',
            'pdfService' => 'App\\Service\\PdfService',
        ]))->withContext('App\\Controller\\IndexController::exportPdf()', $container);
    }
}
