<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndex4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DyCz.w..App\Entity\Index' shared service.
     *
     * @return \App\Entity\Index
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DyCz.w.": it needs an instance of "App\\Entity\\Index" but this type has been excluded in "config/services.yaml".');
    }
}
