<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllerremoveAuthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rsw99ZK.App\Controller\LivreController::removeAuth()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livre' => ['privates', '.errored..service_locator.rsw99ZK.App\\Entity\\Livre', NULL, 'Cannot autowire service ".service_locator.rsw99ZK": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".'],
            'livreAuthRepository' => ['privates', 'App\\Repository\\LivreAuthRepository', 'getLivreAuthRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'livre' => 'App\\Entity\\Livre',
            'livreAuthRepository' => 'App\\Repository\\LivreAuthRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\LivreController::removeAuth()', $container);

        if (isset($container->privates['.service_locator.rsw99ZK.App\\Controller\\LivreController::removeAuth()'])) {
            return $container->privates['.service_locator.rsw99ZK.App\\Controller\\LivreController::removeAuth()'];
        }

        return $container->privates['.service_locator.rsw99ZK.App\\Controller\\LivreController::removeAuth()'] = $instance;
    }
}
