<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotCleControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TjlfE2S.App\Controller\MotCleController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TjlfE2S.App\\Controller\\MotCleController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'motCleRepository' => ['privates', 'App\\Repository\\MotCleRepository', 'getMotCleRepositoryService', true],
            'indexRepository' => ['privates', 'App\\Repository\\IndexRepository', 'getIndexRepositoryService', true],
        ], [
            'motCleRepository' => 'App\\Repository\\MotCleRepository',
            'indexRepository' => 'App\\Repository\\IndexRepository',
        ]))->withContext('App\\Controller\\MotCleController::index()', $container);
    }
}
