<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotCleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ceorNj.App\Controller\MotCleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..ceorNj.App\\Controller\\MotCleController::show()'] = ($container->privates['.service_locator..ceorNj'] ?? $container->load('get_ServiceLocator__CeorNjService'))->withContext('App\\Controller\\MotCleController::show()', $container);
    }
}
