<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotCleRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\MotCleRepository' shared autowired service.
     *
     * @return \App\Repository\MotCleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'MotCleRepository.php';

        return $container->privates['App\\Repository\\MotCleRepository'] = new \App\Repository\MotCleRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
