<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSavRequeteControllershowRequeteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S0S8wkB.App\Controller\SavRequeteController::showRequete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'savRequete' => ['privates', '.errored..service_locator.S0S8wkB.App\\Entity\\SavRequete', NULL, 'Cannot autowire service ".service_locator.S0S8wkB": it needs an instance of "App\\Entity\\SavRequete" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
        ], [
            'savRequete' => 'App\\Entity\\SavRequete',
            'entityManager' => '?',
            'authChecker' => '?',
        ]))->withContext('App\\Controller\\SavRequeteController::showRequete()', $container);

        if (isset($container->privates['.service_locator.S0S8wkB.App\\Controller\\SavRequeteController::showRequete()'])) {
            return $container->privates['.service_locator.S0S8wkB.App\\Controller\\SavRequeteController::showRequete()'];
        }

        return $container->privates['.service_locator.S0S8wkB.App\\Controller\\SavRequeteController::showRequete()'] = $instance;
    }
}
