<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSavRequeteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ukps3KL.App\Controller\SavRequeteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'savRequete' => ['privates', '.errored..service_locator.Ukps3KL.App\\Entity\\SavRequete', NULL, 'Cannot autowire service ".service_locator.Ukps3KL": it needs an instance of "App\\Entity\\SavRequete" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'savRequete' => 'App\\Entity\\SavRequete',
            'doctrine' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\SavRequeteController::edit()', $container);

        if (isset($container->privates['.service_locator.Ukps3KL.App\\Controller\\SavRequeteController::edit()'])) {
            return $container->privates['.service_locator.Ukps3KL.App\\Controller\\SavRequeteController::edit()'];
        }

        return $container->privates['.service_locator.Ukps3KL.App\\Controller\\SavRequeteController::edit()'] = $instance;
    }
}
