<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatutControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ghgjJ8x.App\Controller\StatutController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ghgjJ8x'] ?? $container->load('get_ServiceLocator_GhgjJ8xService'));

        if (isset($container->privates['.service_locator.ghgjJ8x.App\\Controller\\StatutController::edit()'])) {
            return $container->privates['.service_locator.ghgjJ8x.App\\Controller\\StatutController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\StatutController::edit()', $container);

        if (isset($container->privates['.service_locator.ghgjJ8x.App\\Controller\\StatutController::edit()'])) {
            return $container->privates['.service_locator.ghgjJ8x.App\\Controller\\StatutController::edit()'];
        }

        return $container->privates['.service_locator.ghgjJ8x.App\\Controller\\StatutController::edit()'] = $instance;
    }
}
