<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SearchService' shared autowired service.
     *
     * @return \App\Service\SearchService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SearchService.php';

        return $container->privates['App\\Service\\SearchService'] = new \App\Service\SearchService(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['App\\Repository\\SavRequeteRepository'] ?? $container->load('getSavRequeteRepositoryService')));
    }
}
