<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSavRequeteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6QjCRGV.App\Entity\SavRequete' shared service.
     *
     * @return \App\Entity\SavRequete
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6QjCRGV": it needs an instance of "App\\Entity\\SavRequete" but this type has been excluded in "config/services.yaml".');
    }
}
