<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSavRequeteControllerrechercheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6nupgCO.App\Controller\SavRequeteController::recherche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.6nupgCO'] ?? $container->load('get_ServiceLocator_6nupgCOService'));

        if (isset($container->privates['.service_locator.6nupgCO.App\\Controller\\SavRequeteController::recherche()'])) {
            return $container->privates['.service_locator.6nupgCO.App\\Controller\\SavRequeteController::recherche()'];
        }

        $instance = $a->withContext('App\\Controller\\SavRequeteController::recherche()', $container);

        if (isset($container->privates['.service_locator.6nupgCO.App\\Controller\\SavRequeteController::recherche()'])) {
            return $container->privates['.service_locator.6nupgCO.App\\Controller\\SavRequeteController::recherche()'];
        }

        return $container->privates['.service_locator.6nupgCO.App\\Controller\\SavRequeteController::recherche()'] = $instance;
    }
}
