<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllereditUserPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GXpw3O6.App\Controller\UserController::editUserPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'userPasswordHasher' => '?',
            'entityManager' => '?',
            'tokenStorage' => '?',
            'requestStack' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\UserController::editUserPassword()', $container);

        if (isset($container->privates['.service_locator.GXpw3O6.App\\Controller\\UserController::editUserPassword()'])) {
            return $container->privates['.service_locator.GXpw3O6.App\\Controller\\UserController::editUserPassword()'];
        }

        return $container->privates['.service_locator.GXpw3O6.App\\Controller\\UserController::editUserPassword()'] = $instance;
    }
}
