<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllervaliderInscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XwZX.my.App\Controller\UserController::validerInscription()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'repository' => 'App\\Repository\\UserRepository',
            'paginator' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\UserController::validerInscription()', $container);

        if (isset($container->privates['.service_locator.XwZX.my.App\\Controller\\UserController::validerInscription()'])) {
            return $container->privates['.service_locator.XwZX.my.App\\Controller\\UserController::validerInscription()'];
        }

        return $container->privates['.service_locator.XwZX.my.App\\Controller\\UserController::validerInscription()'] = $instance;
    }
}
