<?php

namespace Container8OJblnH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllershowUsersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cE86NDv.App\Controller\UserController::showUsers()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cE86NDv.App\\Controller\\UserController::showUsers()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.cE86NDv.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.cE86NDv": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'security' => '?',
        ]))->withContext('App\\Controller\\UserController::showUsers()', $container);
    }
}
