<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PQP7fxlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PQP7fxl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'motCle' => ['privates', '.errored..service_locator.PQP7fxl.App\\Entity\\MotCle', NULL, 'Cannot autowire service ".service_locator.PQP7fxl": it needs an instance of "App\\Entity\\MotCle" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'motCle' => 'App\\Entity\\MotCle',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.PQP7fxl'])) {
            return $container->privates['.service_locator.PQP7fxl'];
        }

        return $container->privates['.service_locator.PQP7fxl'] = $instance;
    }
}
