<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VhxNdVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vhx_ndV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'authChecker' => '?',
            'tokenStorage' => '?',
            'security' => '?',
        ]);

        if (isset($container->privates['.service_locator.vhx_ndV'])) {
            return $container->privates['.service_locator.vhx_ndV'];
        }

        return $container->privates['.service_locator.vhx_ndV'] = $instance;
    }
}
