<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_93EmIOOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.93EmIOO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livre' => ['privates', '.errored..service_locator.93EmIOO.App\\Entity\\Livre', NULL, 'Cannot autowire service ".service_locator.93EmIOO": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'livre' => 'App\\Entity\\Livre',
            'entityManager' => '?',
            'security' => '?',
        ]);

        if (isset($container->privates['.service_locator.93EmIOO'])) {
            return $container->privates['.service_locator.93EmIOO'];
        }

        return $container->privates['.service_locator.93EmIOO'] = $instance;
    }
}
