<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4lpIoCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C4lpIoC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'historique' => ['privates', '.errored..service_locator.C4lpIoC.App\\Entity\\Historique', NULL, 'Cannot autowire service ".service_locator.C4lpIoC": it needs an instance of "App\\Entity\\Historique" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'historique' => 'App\\Entity\\Historique',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.C4lpIoC'])) {
            return $container->privates['.service_locator.C4lpIoC'];
        }

        return $container->privates['.service_locator.C4lpIoC'] = $instance;
    }
}
