<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteMotControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PQP7fxl.App\Controller\DeleteMotController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.PQP7fxl'] ?? $container->load('get_ServiceLocator_PQP7fxlService'));

        if (isset($container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::delete()'])) {
            return $container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\DeleteMotController::delete()', $container);

        if (isset($container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::delete()'])) {
            return $container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::delete()'];
        }

        return $container->privates['.service_locator.PQP7fxl.App\\Controller\\DeleteMotController::delete()'] = $instance;
    }
}
