<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerexportFicheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zL99E0b.App\Controller\FicheController::exportFiche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'wordExportService' => ['privates', 'App\\Service\\WordService', 'getWordServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'pdfService' => 'App\\Service\\PdfService',
            'wordExportService' => 'App\\Service\\WordService',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\FicheController::exportFiche()', $container);

        if (isset($container->privates['.service_locator.zL99E0b.App\\Controller\\FicheController::exportFiche()'])) {
            return $container->privates['.service_locator.zL99E0b.App\\Controller\\FicheController::exportFiche()'];
        }

        return $container->privates['.service_locator.zL99E0b.App\\Controller\\FicheController::exportFiche()'] = $instance;
    }
}
