<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerdeuxiemeFormulaireActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rvo3vGM.App\Controller\FicheController::deuxiemeFormulaireAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
        ], [
            'doctrine' => '?',
            'security' => '?',
            'authChecker' => '?',
        ]))->withContext('App\\Controller\\FicheController::deuxiemeFormulaireAction()', $container);

        if (isset($container->privates['.service_locator.rvo3vGM.App\\Controller\\FicheController::deuxiemeFormulaireAction()'])) {
            return $container->privates['.service_locator.rvo3vGM.App\\Controller\\FicheController::deuxiemeFormulaireAction()'];
        }

        return $container->privates['.service_locator.rvo3vGM.App\\Controller\\FicheController::deuxiemeFormulaireAction()'] = $instance;
    }
}
