<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerduplicateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B66jqMg.App\Controller\FicheController::duplicate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fiche' => ['privates', '.errored..service_locator.B66jqMg.App\\Entity\\Fiche', NULL, 'Cannot autowire service ".service_locator.B66jqMg": it needs an instance of "App\\Entity\\Fiche" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'fiche' => 'App\\Entity\\Fiche',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\FicheController::duplicate()', $container);

        if (isset($container->privates['.service_locator.B66jqMg.App\\Controller\\FicheController::duplicate()'])) {
            return $container->privates['.service_locator.B66jqMg.App\\Controller\\FicheController::duplicate()'];
        }

        return $container->privates['.service_locator.B66jqMg.App\\Controller\\FicheController::duplicate()'] = $instance;
    }
}
