<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllernewRequeteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Rm2SON.App\Controller\FicheController::newRequete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'entityManager' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\FicheController::newRequete()', $container);

        if (isset($container->privates['.service_locator.6Rm2SON.App\\Controller\\FicheController::newRequete()'])) {
            return $container->privates['.service_locator.6Rm2SON.App\\Controller\\FicheController::newRequete()'];
        }

        return $container->privates['.service_locator.6Rm2SON.App\\Controller\\FicheController::newRequete()'] = $instance;
    }
}
