<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllereditTotalSavReqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hkGLrgv.App\Controller\FicheController::editTotalSavReq()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.hkGLrgv'] ?? $container->load('get_ServiceLocator_HkGLrgvService'));

        if (isset($container->privates['.service_locator.hkGLrgv.App\\Controller\\FicheController::editTotalSavReq()'])) {
            return $container->privates['.service_locator.hkGLrgv.App\\Controller\\FicheController::editTotalSavReq()'];
        }

        $instance = $a->withContext('App\\Controller\\FicheController::editTotalSavReq()', $container);

        if (isset($container->privates['.service_locator.hkGLrgv.App\\Controller\\FicheController::editTotalSavReq()'])) {
            return $container->privates['.service_locator.hkGLrgv.App\\Controller\\FicheController::editTotalSavReq()'];
        }

        return $container->privates['.service_locator.hkGLrgv.App\\Controller\\FicheController::editTotalSavReq()'] = $instance;
    }
}
