<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerexportToDownloadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.skPrLbg.App\Controller\FicheController::exportToDownload()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.skPrLbg.App\\Controller\\FicheController::exportToDownload()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wordExportService' => ['privates', 'App\\Service\\WordService', 'getWordServiceService', true],
        ], [
            'wordExportService' => 'App\\Service\\WordService',
        ]))->withContext('App\\Controller\\FicheController::exportToDownload()', $container);
    }
}
