<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B66jqMg.App\Entity\Fiche' shared service.
     *
     * @return \App\Entity\Fiche
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.B66jqMg": it needs an instance of "App\\Entity\\Fiche" but this type has been excluded in "config/services.yaml".');
    }
}
