<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerhideService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tBssU0B.App\Controller\FicheController::hide()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fiche' => ['privates', '.errored..service_locator.tBssU0B.App\\Entity\\Fiche', NULL, 'Cannot autowire service ".service_locator.tBssU0B": it needs an instance of "App\\Entity\\Fiche" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'fiche' => 'App\\Entity\\Fiche',
            'entityManager' => '?',
            'security' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\FicheController::hide()', $container);

        if (isset($container->privates['.service_locator.tBssU0B.App\\Controller\\FicheController::hide()'])) {
            return $container->privates['.service_locator.tBssU0B.App\\Controller\\FicheController::hide()'];
        }

        return $container->privates['.service_locator.tBssU0B.App\\Controller\\FicheController::hide()'] = $instance;
    }
}
