<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerrechercheDeuxiemeFormulaireActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gU88aXi.App\Controller\FicheController::rechercheDeuxiemeFormulaireAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\FicheController::rechercheDeuxiemeFormulaireAction()', $container);

        if (isset($container->privates['.service_locator.gU88aXi.App\\Controller\\FicheController::rechercheDeuxiemeFormulaireAction()'])) {
            return $container->privates['.service_locator.gU88aXi.App\\Controller\\FicheController::rechercheDeuxiemeFormulaireAction()'];
        }

        return $container->privates['.service_locator.gU88aXi.App\\Controller\\FicheController::rechercheDeuxiemeFormulaireAction()'] = $instance;
    }
}
