<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerresultatRechercheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.grnFogB.App\Controller\FicheController::resultatRecherche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'authChecker' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\FicheController::resultatRecherche()', $container);

        if (isset($container->privates['.service_locator.grnFogB.App\\Controller\\FicheController::resultatRecherche()'])) {
            return $container->privates['.service_locator.grnFogB.App\\Controller\\FicheController::resultatRecherche()'];
        }

        return $container->privates['.service_locator.grnFogB.App\\Controller\\FicheController::resultatRecherche()'] = $instance;
    }
}
