<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerlistUserAuithFicheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y2mEuIt.App\Controller\FicheController::listUserAuithFiche()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ficheRepository' => ['privates', 'App\\Repository\\FicheRepository', 'getFicheRepositoryService', true],
            'authChecker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'ficheRepository' => 'App\\Repository\\FicheRepository',
            'authChecker' => '?',
            'entityManager' => '?',
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\FicheController::listUserAuithFiche()', $container);

        if (isset($container->privates['.service_locator.Y2mEuIt.App\\Controller\\FicheController::listUserAuithFiche()'])) {
            return $container->privates['.service_locator.Y2mEuIt.App\\Controller\\FicheController::listUserAuithFiche()'];
        }

        return $container->privates['.service_locator.Y2mEuIt.App\\Controller\\FicheController::listUserAuithFiche()'] = $instance;
    }
}
