<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheControllerlistCacheeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0X3Xl_x.App\Controller\FicheController::listCachee()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.0X3Xl_x'] ?? $container->load('get_ServiceLocator_0X3XlXService'));

        if (isset($container->privates['.service_locator.0X3Xl_x.App\\Controller\\FicheController::listCachee()'])) {
            return $container->privates['.service_locator.0X3Xl_x.App\\Controller\\FicheController::listCachee()'];
        }

        $instance = $a->withContext('App\\Controller\\FicheController::listCachee()', $container);

        if (isset($container->privates['.service_locator.0X3Xl_x.App\\Controller\\FicheController::listCachee()'])) {
            return $container->privates['.service_locator.0X3Xl_x.App\\Controller\\FicheController::listCachee()'];
        }

        return $container->privates['.service_locator.0X3Xl_x.App\\Controller\\FicheController::listCachee()'] = $instance;
    }
}
