<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C4lpIoC.App\Controller\HistoriqueController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.C4lpIoC'] ?? $container->load('get_ServiceLocator_C4lpIoCService'));

        if (isset($container->privates['.service_locator.C4lpIoC.App\\Controller\\HistoriqueController::edit()'])) {
            return $container->privates['.service_locator.C4lpIoC.App\\Controller\\HistoriqueController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\HistoriqueController::edit()', $container);

        if (isset($container->privates['.service_locator.C4lpIoC.App\\Controller\\HistoriqueController::edit()'])) {
            return $container->privates['.service_locator.C4lpIoC.App\\Controller\\HistoriqueController::edit()'];
        }

        return $container->privates['.service_locator.C4lpIoC.App\\Controller\\HistoriqueController::edit()'] = $instance;
    }
}
