<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllertoggleVisibilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zK1vJJH.App\Controller\IndexController::toggleVisibility()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'index' => ['privates', '.errored..service_locator.zK1vJJH.App\\Entity\\Index', NULL, 'Cannot autowire service ".service_locator.zK1vJJH": it needs an instance of "App\\Entity\\Index" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'index' => 'App\\Entity\\Index',
            'em' => '?',
        ]))->withContext('App\\Controller\\IndexController::toggleVisibility()', $container);

        if (isset($container->privates['.service_locator.zK1vJJH.App\\Controller\\IndexController::toggleVisibility()'])) {
            return $container->privates['.service_locator.zK1vJJH.App\\Controller\\IndexController::toggleVisibility()'];
        }

        return $container->privates['.service_locator.zK1vJJH.App\\Controller\\IndexController::toggleVisibility()'] = $instance;
    }
}
