<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerremoveAuthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..iu_8K_.App\Controller\IndexController::removeAuth()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'index' => ['privates', '.errored..service_locator..iu_8K_.App\\Entity\\Index', NULL, 'Cannot autowire service ".service_locator..iu_8K_": it needs an instance of "App\\Entity\\Index" but this type has been excluded in "config/services.yaml".'],
            'indexAuthRepository' => ['privates', 'App\\Repository\\IndexAuthRepository', 'getIndexAuthRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'index' => 'App\\Entity\\Index',
            'indexAuthRepository' => 'App\\Repository\\IndexAuthRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\IndexController::removeAuth()', $container);

        if (isset($container->privates['.service_locator..iu_8K_.App\\Controller\\IndexController::removeAuth()'])) {
            return $container->privates['.service_locator..iu_8K_.App\\Controller\\IndexController::removeAuth()'];
        }

        return $container->privates['.service_locator..iu_8K_.App\\Controller\\IndexController::removeAuth()'] = $instance;
    }
}
