<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerviewAuthorizedIndexesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sWWUFdD.App\Controller\IndexController::viewAuthorizedIndexes()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sWWUFdD.App\\Controller\\IndexController::viewAuthorizedIndexes()'] = ($container->privates['.service_locator.sWWUFdD'] ?? $container->load('get_ServiceLocator_SWWUFdDService'))->withContext('App\\Controller\\IndexController::viewAuthorizedIndexes()', $container);
    }
}
