<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U2SAl29.App\Controller\IndexController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.U2SAl29'] ?? $container->load('get_ServiceLocator_U2SAl29Service'));

        if (isset($container->privates['.service_locator.U2SAl29.App\\Controller\\IndexController::delete()'])) {
            return $container->privates['.service_locator.U2SAl29.App\\Controller\\IndexController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\IndexController::delete()', $container);

        if (isset($container->privates['.service_locator.U2SAl29.App\\Controller\\IndexController::delete()'])) {
            return $container->privates['.service_locator.U2SAl29.App\\Controller\\IndexController::delete()'];
        }

        return $container->privates['.service_locator.U2SAl29.App\\Controller\\IndexController::delete()'] = $instance;
    }
}
