<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerauthPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3etoGaX.App\Controller\IndexController::authPage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3etoGaX.App\\Controller\\IndexController::authPage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'index' => ['privates', '.errored..service_locator.3etoGaX.App\\Entity\\Index', NULL, 'Cannot autowire service ".service_locator.3etoGaX": it needs an instance of "App\\Entity\\Index" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'indexAuthRepository' => ['privates', 'App\\Repository\\IndexAuthRepository', 'getIndexAuthRepositoryService', true],
        ], [
            'index' => 'App\\Entity\\Index',
            'userRepository' => 'App\\Repository\\UserRepository',
            'indexAuthRepository' => 'App\\Repository\\IndexAuthRepository',
        ]))->withContext('App\\Controller\\IndexController::authPage()', $container);
    }
}
