<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexAuthRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\IndexAuthRepository' shared autowired service.
     *
     * @return \App\Repository\IndexAuthRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'IndexAuthRepository.php';

        return $container->privates['App\\Repository\\IndexAuthRepository'] = new \App\Repository\IndexAuthRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
