<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllersaveAuthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DyCz.w..App\Controller\IndexController::saveAuth()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'index' => ['privates', '.errored..service_locator.DyCz.w..App\\Entity\\Index', NULL, 'Cannot autowire service ".service_locator.DyCz.w.": it needs an instance of "App\\Entity\\Index" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'index' => 'App\\Entity\\Index',
            'userRepository' => 'App\\Repository\\UserRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\IndexController::saveAuth()', $container);

        if (isset($container->privates['.service_locator.DyCz.w..App\\Controller\\IndexController::saveAuth()'])) {
            return $container->privates['.service_locator.DyCz.w..App\\Controller\\IndexController::saveAuth()'];
        }

        return $container->privates['.service_locator.DyCz.w..App\\Controller\\IndexController::saveAuth()'] = $instance;
    }
}
