<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllermakeIndexInvisibleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MtVeqgQ.App\Controller\IndexController::makeIndexInvisible()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'indexRepository' => ['privates', 'App\\Repository\\IndexRepository', 'getIndexRepositoryService', true],
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'indexRepository' => 'App\\Repository\\IndexRepository',
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\IndexController::makeIndexInvisible()', $container);

        if (isset($container->privates['.service_locator.MtVeqgQ.App\\Controller\\IndexController::makeIndexInvisible()'])) {
            return $container->privates['.service_locator.MtVeqgQ.App\\Controller\\IndexController::makeIndexInvisible()'];
        }

        return $container->privates['.service_locator.MtVeqgQ.App\\Controller\\IndexController::makeIndexInvisible()'] = $instance;
    }
}
