<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllertoggleVisibilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GeXPOoV.App\Controller\LivreController::toggleVisibility()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livre' => ['privates', '.errored..service_locator.GeXPOoV.App\\Entity\\Livre', NULL, 'Cannot autowire service ".service_locator.GeXPOoV": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'livre' => 'App\\Entity\\Livre',
            'em' => '?',
        ]))->withContext('App\\Controller\\LivreController::toggleVisibility()', $container);

        if (isset($container->privates['.service_locator.GeXPOoV.App\\Controller\\LivreController::toggleVisibility()'])) {
            return $container->privates['.service_locator.GeXPOoV.App\\Controller\\LivreController::toggleVisibility()'];
        }

        return $container->privates['.service_locator.GeXPOoV.App\\Controller\\LivreController::toggleVisibility()'] = $instance;
    }
}
