<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllereditAuthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6u0cX_B.App\Controller\LivreController::editAuth()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.6u0cX_B'] ?? $container->load('get_ServiceLocator_6u0cXBService'));

        if (isset($container->privates['.service_locator.6u0cX_B.App\\Controller\\LivreController::editAuth()'])) {
            return $container->privates['.service_locator.6u0cX_B.App\\Controller\\LivreController::editAuth()'];
        }

        $instance = $a->withContext('App\\Controller\\LivreController::editAuth()', $container);

        if (isset($container->privates['.service_locator.6u0cX_B.App\\Controller\\LivreController::editAuth()'])) {
            return $container->privates['.service_locator.6u0cX_B.App\\Controller\\LivreController::editAuth()'];
        }

        return $container->privates['.service_locator.6u0cX_B.App\\Controller\\LivreController::editAuth()'] = $instance;
    }
}
