<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vNjvjLJ.App\Controller\LivreController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.vNjvjLJ'] ?? $container->load('get_ServiceLocator_VNjvjLJService'));

        if (isset($container->privates['.service_locator.vNjvjLJ.App\\Controller\\LivreController::new()'])) {
            return $container->privates['.service_locator.vNjvjLJ.App\\Controller\\LivreController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\LivreController::new()', $container);

        if (isset($container->privates['.service_locator.vNjvjLJ.App\\Controller\\LivreController::new()'])) {
            return $container->privates['.service_locator.vNjvjLJ.App\\Controller\\LivreController::new()'];
        }

        return $container->privates['.service_locator.vNjvjLJ.App\\Controller\\LivreController::new()'] = $instance;
    }
}
