<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotCle2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PQP7fxl.App\Entity\MotCle' shared service.
     *
     * @return \App\Entity\MotCle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PQP7fxl": it needs an instance of "App\\Entity\\MotCle" but this type has been excluded in "config/services.yaml".');
    }
}
