<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileUserControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8m8R3s_.App\Controller\ProfileUserController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.8m8R3s_'] ?? $container->load('get_ServiceLocator_8m8R3sService'));

        if (isset($container->privates['.service_locator.8m8R3s_.App\\Controller\\ProfileUserController::edit()'])) {
            return $container->privates['.service_locator.8m8R3s_.App\\Controller\\ProfileUserController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ProfileUserController::edit()', $container);

        if (isset($container->privates['.service_locator.8m8R3s_.App\\Controller\\ProfileUserController::edit()'])) {
            return $container->privates['.service_locator.8m8R3s_.App\\Controller\\ProfileUserController::edit()'];
        }

        return $container->privates['.service_locator.8m8R3s_.App\\Controller\\ProfileUserController::edit()'] = $instance;
    }
}
