<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatutControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xMcSKQH.App\Controller\StatutController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xMcSKQH.App\\Controller\\StatutController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statutRepository' => ['privates', 'App\\Repository\\StatutRepository', 'getStatutRepositoryService', true],
        ], [
            'statutRepository' => 'App\\Repository\\StatutRepository',
        ]))->withContext('App\\Controller\\StatutController::index()', $container);
    }
}
