<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSavRequeteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..iIUMTE.App\Controller\SavRequeteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..iIUMTE.App\\Controller\\SavRequeteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'savRequeteRepository' => ['privates', 'App\\Repository\\SavRequeteRepository', 'getSavRequeteRepositoryService', true],
        ], [
            'savRequeteRepository' => 'App\\Repository\\SavRequeteRepository',
        ]))->withContext('App\\Controller\\SavRequeteController::index()', $container);
    }
}
