<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatutControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FpXW4xS.App\Controller\StatutController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FpXW4xS.App\\Controller\\StatutController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statut' => ['privates', '.errored..service_locator.FpXW4xS.App\\Entity\\Statut', NULL, 'Cannot autowire service ".service_locator.FpXW4xS": it needs an instance of "App\\Entity\\Statut" but this type has been excluded in "config/services.yaml".'],
        ], [
            'statut' => 'App\\Entity\\Statut',
        ]))->withContext('App\\Controller\\StatutController::show()', $container);
    }
}
