<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerlogoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GBAwazK.App\Controller\SecurityController::logout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GBAwazK.App\\Controller\\SecurityController::logout()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'requestStack' => '?',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\SecurityController::logout()', $container);
    }
}
