<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerautoriserUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6taa_tu.App\Controller\UserController::autoriserUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'doctrine' => '?',
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\UserController::autoriserUser()', $container);

        if (isset($container->privates['.service_locator.6taa_tu.App\\Controller\\UserController::autoriserUser()'])) {
            return $container->privates['.service_locator.6taa_tu.App\\Controller\\UserController::autoriserUser()'];
        }

        return $container->privates['.service_locator.6taa_tu.App\\Controller\\UserController::autoriserUser()'] = $instance;
    }
}
