<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllernewAutorisationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.epBu9VJ.App\Controller\UserController::newAutorisation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.epBu9VJ.App\\Controller\\UserController::newAutorisation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'security' => '?',
        ]))->withContext('App\\Controller\\UserController::newAutorisation()', $container);
    }
}
