<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vhx_ndV.App\Controller\UserController::deleteUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.vhx_ndV'] ?? $container->load('get_ServiceLocator_VhxNdVService'));

        if (isset($container->privates['.service_locator.vhx_ndV.App\\Controller\\UserController::deleteUser()'])) {
            return $container->privates['.service_locator.vhx_ndV.App\\Controller\\UserController::deleteUser()'];
        }

        $instance = $a->withContext('App\\Controller\\UserController::deleteUser()', $container);

        if (isset($container->privates['.service_locator.vhx_ndV.App\\Controller\\UserController::deleteUser()'])) {
            return $container->privates['.service_locator.vhx_ndV.App\\Controller\\UserController::deleteUser()'];
        }

        return $container->privates['.service_locator.vhx_ndV.App\\Controller\\UserController::deleteUser()'] = $instance;
    }
}
