<?php

namespace ContainerXyAsM64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWordServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WordService' shared autowired service.
     *
     * @return \App\Service\WordService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WordService.php';

        return $container->privates['App\\Service\\WordService'] = new \App\Service\WordService(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
