<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618085040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fichemotcle DROP CONSTRAINT fichemotcle_pkey');
        $this->addSql('ALTER TABLE fichemotcle ALTER precision DROP NOT NULL');
        $this->addSql('ALTER TABLE fichemotcle ADD PRIMARY KEY (fiche, motcle)');
        $this->addSql('ALTER INDEX IF EXISTS idx_b79389f0df522508 RENAME TO "IDX_B42EA8D64C13CC78"');
        $this->addSql('ALTER INDEX IF EXISTS idx_b79389f0fe94535c RENAME TO "IDX_B42EA8D64496AE75"');
        $this->addSql('ALTER TABLE historique ADD CONSTRAINT FK_EDBFD5ECDF522508 FOREIGN KEY (fiche_id) REFERENCES fiche (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_EDBFD5ECDF522508 ON historique (fiche_id)');
        $this->addSql('ALTER TABLE livre_auth DROP CONSTRAINT fk_f2b94bd437d925cb');
        $this->addSql('ALTER TABLE livre_auth ADD CONSTRAINT FK_F2B94BD437D925CB FOREIGN KEY (livre_id) REFERENCES livre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mot_cle DROP CONSTRAINT fk_af92d22a84337261');
        $this->addSql('ALTER TABLE mot_cle ADD CONSTRAINT FK_AF92D22A84337261 FOREIGN KEY (index_id) REFERENCES index (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ALTER active SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER valide SET NOT NULL');
        $this->addSql('DROP INDEX IF EXISTS idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX IF EXISTS idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX IF EXISTS idx_75ea56e0e3bd61ce');
        $this->addSql(<<<'SQL'
        DO $$
        BEGIN
        IF to_regclass('public.messenger_messages') IS NOT NULL THEN
            IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
                AND table_name = 'messenger_messages'
                AND column_name = 'id'
                AND is_identity = 'NO'
            ) THEN
            ALTER TABLE messenger_messages ALTER COLUMN id DROP DEFAULT;
            ALTER TABLE messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END IF;
        END $$;
        SQL);
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fichemotcle DROP CONSTRAINT fichemotcle_pkey');
        $this->addSql('ALTER TABLE fichemotcle ALTER "precision" SET NOT NULL');
        $this->addSql('ALTER TABLE fichemotcle ADD PRIMARY KEY (fiche, motcle, "precision")');
        $this->addSql('ALTER INDEX IF EXISTS idx_b42ea8d64496ae75 RENAME TO idx_b79389f0fe94535c');
        $this->addSql('ALTER INDEX IF EXISTS idx_b42ea8d64c13cc78 RENAME TO idx_b79389f0df522508');
        $this->addSql('ALTER TABLE historique DROP CONSTRAINT FK_EDBFD5ECDF522508');
        $this->addSql('DROP INDEX IF EXISTS IDX_EDBFD5ECDF522508');
        $this->addSql('ALTER TABLE livre_auth DROP CONSTRAINT FK_F2B94BD437D925CB');
        $this->addSql('ALTER TABLE livre_auth ADD CONSTRAINT fk_f2b94bd437d925cb FOREIGN KEY (livre_id) REFERENCES livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('ALTER TABLE mot_cle DROP CONSTRAINT FK_AF92D22A84337261');
        $this->addSql('ALTER TABLE mot_cle ADD CONSTRAINT fk_af92d22a84337261 FOREIGN KEY (index_id) REFERENCES index (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ALTER active DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER valide DROP NOT NULL');
    }
}